# Generated by Django 2.0.6 on 2018-07-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
